#!/usr/bin/env bash
#
# Build an Arch Linux pacman package (.pkg.tar.zst) from the unpacked
# Electron app produced by `task build`. Invoked via `task build:arch`.
#
# We generate the PKGBUILD on the fly instead of committing one because:
#   1. The `pkgver=` and `arch=` fields must track package.json + host arch.
#   2. The PKGBUILD's package() function references the absolute path of the
#      already-built app under out/, which differs per checkout.
#   3. There is no upstream source to download — makepkg's normal build()
#      step is skipped; package() just copies the pre-existing binaries
#      into $pkgdir. This is the same pattern electron-builder uses.
#
# Naming convention: the app, binary, .desktop name, and pacman pkgname are
# all "zpass" (lowercase). forge.config.ts pins both `name` and
# `executableName` to that value so `out/zpass-linux-<arch>/zpass` is the
# stable layout this script targets.
#
# Output: out/make/arch/zpass-<version>-1-<arch>.pkg.tar.zst
#
# Install / uninstall after build:
#   sudo pacman -U  out/make/arch/zpass-*.pkg.tar.zst
#   sudo pacman -Rs zpass

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Map host machine -> (Node arch dir name, pacman arch field). Node arch is
# used because `task build` writes to out/zpass-linux-<node-arch>/, matching
# the convention forced on us by Electron Packager and `process.arch`.
case "$(uname -m)" in
  x86_64)  NODE_ARCH=x64;   PKG_ARCH=x86_64 ;;
  aarch64) NODE_ARCH=arm64; PKG_ARCH=aarch64 ;;
  i686)    NODE_ARCH=ia32;  PKG_ARCH=i686 ;;
  *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
esac

APP_DIR="${REPO_ROOT}/out/zpass-linux-${NODE_ARCH}"
if [[ ! -d "$APP_DIR" ]]; then
  echo "missing $APP_DIR; run 'task build' first" >&2
  exit 1
fi

# node, not jq/grep: node is already a dev dependency and parses JSON
# correctly without ad-hoc regex.
VERSION="$(node -p "require('${REPO_ROOT}/package.json').version")"

BUILD_DIR="${REPO_ROOT}/out/make/arch"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

# Heredoc with quoted EOF on the inner $-references (\$pkgdir, \$size) so
# they reach the PKGBUILD verbatim and are expanded by bash inside makepkg.
# Unquoted variables (${VERSION}, ${PKG_ARCH}, ${REPO_ROOT}, ${APP_DIR})
# are expanded here, freezing them into the file.
cat >"${BUILD_DIR}/PKGBUILD" <<EOF
# Auto-generated by scripts/make-arch.sh — do not edit by hand.
pkgname=zpass
pkgver=${VERSION}
pkgrel=1
pkgdesc="ZPass — zero-knowledge desktop password manager"
arch=('${PKG_ARCH}')
url="https://github.com/zerx-lab/zpass"
license=('MIT')
# Electron's runtime deps on Linux. nss + libxss + libnotify cover the
# Chromium sandbox/notification surface; xdg-utils for xdg-open from links.
depends=('gtk3' 'nss' 'libxss' 'libnotify' 'xdg-utils')
# Skip makepkg's default post-processing: the Electron binaries are already
# stripped (-s -w on Go, Electron itself ships release builds), and trying
# to re-strip .so files inside Electron breaks ASAR integrity checks.
options=('!strip' '!debug' '!emptydirs')
source=()

package() {
  # 1. App tree under /opt/zpass (FHS-compliant location for third-party apps).
  install -dm755 "\$pkgdir/opt/zpass"
  cp -a "${APP_DIR}/." "\$pkgdir/opt/zpass/"

  # Normalise permissions. \`cp -a\` preserves source modes; if the developer
  # building the package has a restrictive umask (077 / 027), the top-level
  # /opt/zpass dir ends up owner-only (drwx------), and the desktop launcher
  # fails with "无法找到程序 'zpass'" because /usr/bin/zpass -> /opt/zpass/zpass
  # is unreachable for non-root users. a+rX = world-read + execute on dirs
  # (and on files that already have x), which is the right minimum for an
  # installed-system-wide package.
  chmod -R a+rX "\$pkgdir/opt/zpass"

  # The Chromium SUID sandbox helper MUST be setuid root or Electron refuses
  # to start with "The SUID sandbox helper binary was found, but is not
  # configured correctly". Pacman preserves these bits on install. Run this
  # AFTER the chmod -R above, otherwise the recursive chmod clobbers the
  # setuid bit.
  chmod 4755 "\$pkgdir/opt/zpass/chrome-sandbox"

  # 2. /usr/bin shim so the .desktop file's Exec=zpass resolves on \$PATH.
  install -dm755 "\$pkgdir/usr/bin"
  ln -s /opt/zpass/zpass "\$pkgdir/usr/bin/zpass"

  # 3. Desktop entry + hicolor theme icons. The .desktop Icon= field is
  # "zpass", which xdg looks up against /usr/share/icons/hicolor/*/apps/.
  install -Dm644 "${REPO_ROOT}/assets/logo/zpass.desktop" \\
    "\$pkgdir/usr/share/applications/zpass.desktop"

  for size in 16 32 48 64 128 256 512; do
    install -Dm644 "${REPO_ROOT}/assets/logo/png/zpass-\${size}.png" \\
      "\$pkgdir/usr/share/icons/hicolor/\${size}x\${size}/apps/zpass.png"
  done

  # 4. Browser native messaging host manifest.
  #
  # Without these JSON files the browser extension can't find
  # /opt/zpass/resources/bin/linux-*/zpass-native-host and reports
  # "Specified native messaging host not found".
  #
  # The Chrome extension ID is deterministic because wxt.config.ts pins the
  # extension's public key (see extension/wxt.config.ts). The Firefox id is
  # the fixed value declared in the same file.
  #
  # Install paths are the system-wide locations each browser scans on Linux:
  #   Chromium-family: /etc/<browser>/native-messaging-hosts/<host>.json
  #     - chromium      -> /etc/chromium/native-messaging-hosts/
  #     - google-chrome -> /etc/opt/chrome/native-messaging-hosts/
  #     - microsoft-edge-> /etc/opt/edge/native-messaging-hosts/
  #     - brave         -> /etc/opt/chrome/native-messaging-hosts/ (shares chrome dir)
  #     - vivaldi       -> /etc/opt/chrome/native-messaging-hosts/ (same)
  #   Firefox:         /usr/lib/mozilla/native-messaging-hosts/<host>.json
  local host_name="com.zerx_lab.zpass"
  local host_bin="/opt/zpass/resources/bin/linux-${NODE_ARCH}/zpass-native-host"
  local chrome_ext_id="nlnkemblgkpcpepbholdkcmcfgjhgfda"
  local firefox_ext_id="zpass-extension@zerx-lab.local"

  local chromium_manifest="{
  \"name\": \"\${host_name}\",
  \"description\": \"ZPass native messaging host\",
  \"path\": \"\${host_bin}\",
  \"type\": \"stdio\",
  \"allowed_origins\": [\"chrome-extension://\${chrome_ext_id}/\"]
}"
  local firefox_manifest="{
  \"name\": \"\${host_name}\",
  \"description\": \"ZPass native messaging host\",
  \"path\": \"\${host_bin}\",
  \"type\": \"stdio\",
  \"allowed_extensions\": [\"\${firefox_ext_id}\"]
}"

  for dir in \\
    "/etc/chromium/native-messaging-hosts" \\
    "/etc/opt/chrome/native-messaging-hosts" \\
    "/etc/opt/edge/native-messaging-hosts"
  do
    install -dm755 "\$pkgdir\${dir}"
    printf '%s\\n' "\${chromium_manifest}" > "\$pkgdir\${dir}/\${host_name}.json"
    chmod 0644 "\$pkgdir\${dir}/\${host_name}.json"
  done

  install -dm755 "\$pkgdir/usr/lib/mozilla/native-messaging-hosts"
  printf '%s\\n' "\${firefox_manifest}" \\
    > "\$pkgdir/usr/lib/mozilla/native-messaging-hosts/\${host_name}.json"
  chmod 0644 "\$pkgdir/usr/lib/mozilla/native-messaging-hosts/\${host_name}.json"
}
EOF

# makepkg refuses to run as root by default (good); --noconfirm avoids the
# "edit PKGBUILD?" prompt; --force overwrites any prior .pkg.tar.zst.
# --nodeps skips the runtime-deps install check: depends=(gtk3 nss ...) are
# needed on the *target* system, not the build host. Without this, CI's slim
# archlinux:latest container (only base-devel + nodejs) aborts with
# "Could not resolve all dependencies". Pacman still records the deps in
# the .pkg.tar.zst metadata, so install-time resolution is unaffected.
cd "$BUILD_DIR"
makepkg --force --noconfirm --clean --nodeps

echo
echo "==> built: $(ls "${BUILD_DIR}"/zpass-*.pkg.tar.zst)"
echo "    install:  sudo pacman -U $(ls "${BUILD_DIR}"/zpass-*.pkg.tar.zst)"
