// ZPass 桌面客户端 —— 英文字典
// 完整字典从 ZPassDesign/src/i18n.jsx 迁移，当前为骨架占位。
// 新增键值时必须同步补全 zh.ts，否则会 fallback 显示 key 名。

export const en = {
	// Brand
	brand_tag: "Zero-knowledge vault",

	// Sidebar — Navigation
	nav_workspace: "Workspace",
	nav_all_items: "All items",
	nav_generator: "Generator",
	nav_security: "Security",
	nav_categories: "Categories",
	nav_logins: "Logins",
	nav_cards: "Cards",
	nav_notes: "Notes",
	nav_identities: "Identities",
	nav_ssh: "SSH keys",
	nav_passkeys: "Passkeys",
	nav_totp: "Authenticator",
	nav_totp_category: "Authenticators",
	nav_work: "Work",
	nav_personal: "Personal",
	nav_tier: "Pro · Local-first",
	nav_lock_title: "Lock vault (⌘L)",

	// Sidebar —— 左下角账户区（guest 模式 / 登录入口）
	sidebar_local_mode: "Local mode",
	sidebar_local_mode_sub: "This device only",
	sidebar_signin: "Sign in",
	sidebar_collapse: "Collapse sidebar",
	sidebar_expand: "Expand sidebar",

	// Topbar
	topbar_vault: "Vault",
	topbar_generator: "Generator",
	topbar_totp: "Authenticator",
	topbar_security: "Security",
	topbar_settings: "Settings",
	topbar_search: "Search or jump…",
	topbar_new: "New",
	topbar_theme_light: "Switch to light",
	topbar_theme_dark: "Switch to dark",
	topbar_notifications: "Notifications",

	// Vault
	vault_title: "Vault",
	vault_empty: "No items",
	vault_empty_hint: "Add your first login to get started.",
	vault_loading: "Loading…",
	vault_error: "Failed to load vault",
	vault_search_placeholder: "Search items",
	vault_new_btn: "New item",
	vault_filter_all: "All",
	vault_filter_login: "Logins",
	vault_filter_card: "Cards",
	vault_filter_note: "Notes",
	vault_filter_identity: "Identities",
	vault_filter_ssh: "SSH",
	vault_filter_passkey: "Passkeys",
	vault_filter_totp: "Authenticator",
	vault_filter_fav: "Favorites",
	vault_count: "{{count}} items",
	vault_count_one: "{{count}} item",
	vault_lock_btn: "Lock",
	detail_empty: "Select an item",
	detail_username: "Username",
	detail_password: "Password",
	detail_url: "Website",
	detail_notes: "Notes",
	detail_copy: "Copy",
	detail_copied: "Copied",
	detail_reveal: "Reveal",
	detail_hide: "Hide",
	detail_edit: "Edit",
	detail_delete: "Delete",
	detail_delete_confirm: "Delete this item permanently?",

	// New / Edit item dialog —— 多类型条目表单
	newlogin_title: "New login",
	// 动态标题：用 i18next 插值组合，{{type}} 由调用方传入对应 newlogin_type_xxx 的翻译值。
	// 例：t("newitem_title", { type: t("newlogin_type_card") }) → "New Credit card"
	newitem_title: "New {{type}}",
	newlogin_sub: "All fields are end-to-end encrypted before being saved.",
	newlogin_name: "Name",
	newlogin_name_placeholder: "e.g. GitHub",
	newlogin_username: "Username or email",
	newlogin_username_placeholder: "alex@example.com",
	newlogin_password: "Password",
	newlogin_password_placeholder: "Strong password",
	newlogin_url: "Website",
	newlogin_url_placeholder: "github.com",
	newlogin_notes: "Notes",
	newlogin_notes_placeholder: "Optional",
	newlogin_save: "Save",
	newlogin_saving: "Encrypting…",
	newlogin_cancel: "Cancel",
	newlogin_err_required: "Name and password are required",
	newlogin_generate: "Generate",
	newlogin_generate_hint: "Generate a strong password",
	newlogin_type_login: "Login",
	newlogin_type_card: "Credit card",
	newlogin_type_note: "Secure note",
	newlogin_type_identity: "Identity",
	newlogin_type_ssh: "SSH key",
	newlogin_type_passkey: "Passkey",
	newlogin_type_totp: "Authenticator",

	// Field labels (per type) —— 每种条目类型各自的字段标签
	// 此前所有类型都复用 newlogin_username/password/url/notes，导致
	// "CVV"显示成"密码"、"卡号"显示成"密码"等错位。每个字段独立 key 后
	// 视觉与语义对齐。
	field_card_holder: "Cardholder",
	field_card_holder_placeholder: "Name on card",
	field_card_number: "Card number",
	field_card_number_placeholder: "1234 5678 9012 3456",
	field_card_expiry: "Expiry",
	field_card_expiry_placeholder: "MM / YY",
	field_card_cvv: "CVV",
	field_card_cvv_placeholder: "•••",

	field_identity_fullname: "Full name",
	field_identity_fullname_placeholder: "First Last",
	field_identity_email: "Email",
	field_identity_email_placeholder: "you@example.com",
	field_identity_phone: "Phone",
	field_identity_phone_placeholder: "+1 555 0100",

	field_ssh_username: "Username",
	field_ssh_username_placeholder: "git",
	field_ssh_private_key: "Private key",
	field_ssh_private_key_placeholder: "-----BEGIN OPENSSH PRIVATE KEY-----",
	field_ssh_passphrase: "Passphrase",
	field_ssh_passphrase_placeholder: "Optional key passphrase",
	field_ssh_host: "Host",
	field_ssh_host_placeholder: "github.com",
	field_passkey_rp_id: "Relying party ID",
	field_passkey_rp_id_placeholder: "example.com",
	field_passkey_user_name: "Account",
	field_passkey_user_name_placeholder: "user@example.com",
	field_passkey_credential_id: "Credential ID",
	field_passkey_credential_id_placeholder: "Generated by ZPass",

	// Edit item
	edit_title: "Edit item",
	edit_sub: "Changes are re-encrypted before being saved.",
	edit_save: "Save changes",
	edit_saving: "Saving…",
	edit_cancel: "Cancel",
	edit_btn: "Edit",

	// Vault keyboard hints
	// ---------------------------------------------------------------------------
	// Modifier key glyphs (⌘ / Ctrl / Shift…) are rendered per-platform via
	// lib/keys.ts::formatShortcut() — they're a platform property, not a language
	// one, so we do NOT hardcode them in the i18n dictionary. Only the localized
	// action label is stored here; UI composes "{shortcut} {label}" at render time.
	vault_kbd_navigate: "↑↓ navigate · ⏎ open",
	vault_kbd_copy_pw_label: "Copy password",
	vault_kbd_copy_user_label: "Copy username",
	vault_kbd_open_label: "Navigate / open",
	vault_kbd_new_label: "New item",
	ctx_new_item: "New item",
	ctx_copy_username: "Copy username",
	ctx_copy_password: "Copy password",
	ctx_copy_url: "Copy website",

	// Generic
	common_close: "Close",
	common_optional: "optional",

	// Unlock
	unlock_greeting: "Welcome back",
	unlock_sub: "Enter your master password to unlock",
	unlock_placeholder: "Master password",
	unlock_bio: "Use biometrics",
	unlock_switch: "Switch account",
	unlock_btn: "Unlock",
	unlock_loading: "Unlocking…",
	unlock_brand_sub: "End-to-end encrypted · Zero knowledge",
	unlock_foot: "Your passwords never leave this device",
	unlock_err_invalid: "Incorrect master password",
	unlock_err_unknown: "Unable to unlock. Please try again.",

	// Create master password (first run)
	unlock_create_greeting: "Create your master password",
	unlock_create_sub:
		"This password protects every item in your vault. We never store, transmit, or recover it — choose carefully.",
	unlock_create_placeholder: "Master password (min 8 chars)",
	unlock_create_confirm_placeholder: "Confirm master password",
	unlock_create_btn: "Create vault",
	unlock_create_loading: "Encrypting…",
	unlock_create_warn:
		"Zero-knowledge: if you forget this password, your data cannot be recovered.",
	unlock_create_err_mismatch: "The two passwords don't match",
	unlock_create_err_weak: "Master password must be at least 8 characters",

	// Generator —— 密码生成器（完整实现）
	gen_title: "Password generator",
	gen_sub: "Create strong, memorable, single-use secrets",
	gen_badge: "Local · Cryptographic RNG",
	gen_mode_password: "Password",
	gen_mode_passphrase: "Passphrase",
	gen_mode_pin: "PIN",
	gen_length: "Length",
	gen_words: "Words",
	gen_chars: "chars",
	gen_separator: "Separator",
	gen_lower: "Lowercase",
	gen_lower_sub: "a b c d",
	gen_upper: "Uppercase",
	gen_upper_sub: "A B C D",
	gen_numbers: "Numbers",
	gen_numbers_sub: "0 1 2 3",
	gen_symbols: "Symbols",
	gen_symbols_sub: "! @ # $",
	gen_avoid_amb: "Avoid look-alikes",
	gen_avoid_amb_sub: "Skip 0/O/1/l/I",
	gen_avoid_rep: "No repeats",
	gen_avoid_rep_sub: "Each char once",
	gen_capitalize: "Capitalize",
	gen_capitalize_sub: "Brave-Ocean",
	gen_include_number: "Append number",
	gen_include_number_sub: "Brave-Ocean-42",
	gen_regen: "Regenerate",
	gen_copy: "Copy",
	gen_copy_all: "Copy all",
	gen_count: "Count",
	gen_save: "Save to vault",
	gen_analysis: "Analysis",
	gen_recent: "Recent",
	gen_recent_empty: "No recent passwords yet",
	gen_tips: "Tips",
	gen_tip_1: "// Long passphrases beat short complex passwords",
	gen_tip_2: "// Each site deserves a unique password",
	gen_tip_3: "// Random > clever — no patterns are safe",
	gen_copied: "Password copied",
	gen_saved: "Saved to vault",
	gen_section_options: "Options",

	// Strength —— 密码强度
	strength_weak: "Weak",
	strength_fair: "Fair",
	strength_strong: "Strong",
	strength_excellent: "Excellent",
	strength_entropy: "entropy",
	strength_crack: "crack time",
	strength_empty_hint: "Enter or generate a password to see strength",

	// Health / Security Center —— 完整实现
	health_title: "Security center",
	health_lede_prefix: "A calm snapshot of your vault health.",
	health_lede_mid: "Rotate weak items, clean reused ones, enable 2FA.",
	health_score_k: "Overall score",
	health_score_week: "This week",
	health_score_fix: "Fix now",
	health_score_desc: "Based on strength, reuse, age and 2FA coverage.",
	health_breached_k: "Breached",
	health_breached_d: "Items found in known breach dumps.",
	health_2fa_k: "2FA coverage",
	health_2fa_d: "Logins with a second factor enabled.",
	health_tile_weak: "Weak passwords",
	health_tile_reused: "Reused passwords",
	health_tile_old: "Old passwords",
	health_tile_no2fa: "Missing 2FA",
	health_actions: "Actions",
	health_actions_found: "No action items",
	health_rotate_all: "Rotate all",
	health_fix: "Fix",
	health_breach_monitor: "Breach monitor",
	health_breach_src: "Source · HIBP",
	health_affected: "Affected",
	health_no_match: "No matching breaches",
	health_activity: "Recent activity",
	health_local: "Local",
	health_dist: "Distribution",
	health_score_grade_a: "Excellent",
	health_score_grade_b: "Good",
	health_score_grade_c: "Needs attention",
	health_score_grade_d: "At risk",
	health_no_logins: "Add a login to start tracking your vault health.",
	health_open_item: "Open",
	health_sev_breach: "Breached",
	health_sev_weak: "Weak",
	health_sev_reused: "Reused",
	health_sev_old: "Stale",
	health_sev_no2fa: "No 2FA",
	health_action_empty: "All clear · no urgent issues",
	health_dist_empty: "No login items to chart yet",
	health_age_recent: "< 90d",
	health_age_mid: "< 1y",
	health_age_old: "> 1y",
	health_breach_scanning: "Scanning…",
	health_breach_scan: "Scan passwords",
	health_breach_rescan: "Re-scan",
	health_breach_last_scan: "Last scan",
	health_breach_found: "{{count}} password found in known breaches",
	health_breach_found_plural: "{{count}} passwords found in known breaches",
	health_breach_clear: "No passwords found in known breaches",
	health_breach_count: "Exposed {{count}} times",
	health_breach_error: "Check failed",
	health_breach_privacy:
		"Only the first 5 characters of each password's SHA-1 hash are sent — HIBP never sees your actual passwords.",
	health_breach_powered: "Powered by Have I Been Pwned",

	// Toast 通用文案（store.pushToast 的 text 内容）
	toast_copied: "Copied to clipboard",
	toast_copied_username: "Username copied",
	toast_copied_password: "Password copied · clears in 30s",
	toast_copied_url: "Website copied",
	toast_copied_generic: "{{label}} copied",
	// TOTP 复制反馈：6 位 OTP 走临时剪贴板（30s 自动清空）；secret 不入此提示
	toast_copied_totp: "One-time code copied · clears in 30s",
	toast_locked: "Vault locked",
	toast_saved: "Saved",
	toast_deleted: "Item deleted",
	toast_generated: "New password generated",
	toast_copy_failed: "Couldn't access clipboard",

	// CmdK —— 命令面板
	cmdk_placeholder: "Type a command or search…",
	// 无障碍：视觉隐藏的 Radix Dialog Title / Description，用于屏幕阅读器
	cmdk_a11y_title: "Command palette",
	cmdk_a11y_description:
		"Search vault items or run a command. Use arrow keys to navigate, Enter to select, Escape to close.",
	cmdk_empty: "No results",
	cmdk_commands: "Commands",
	cmdk_items: "Items",
	cmdk_nav_vault: "Go to vault",
	cmdk_nav_gen: "Open generator",
	cmdk_nav_health: "Open security center",
	cmdk_nav_new: "New item",
	cmdk_nav_lock: "Lock vault",
	cmdk_nav_theme: "Toggle theme",
	cmdk_nav_lang: "Toggle language",
	cmdk_nav_settings: "Open settings",
	cmdk_navigate: "Navigate",
	cmdk_select: "Select",
	cmdk_toggle: "Toggle",

	// 通用动作
	nav_sign_out: "Sign out",

	// ── Account menu (Sidebar) — Import / Export ──
	menu_import: "Import data…",
	menu_export: "Export vault…",

	// ── Import dialog ──
	import_title: "Import data",
	import_sub: "Bring in entries from another password manager.",
	import_format_label: "Format",
	import_format_bw: "Bitwarden JSON",
	import_format_bw_hint:
		"Unencrypted .json export from Bitwarden Web Vault, Desktop or CLI.",
	import_format_cxf: "FIDO Credential Exchange (CXF) — coming soon",
	import_choose: "Choose file…",
	import_drop: "or drop a .json file here",
	import_no_file: "No file selected",
	import_parse_error:
		"Could not parse the file. Make sure it's a valid Bitwarden JSON export.",
	import_encrypted:
		"This file is encrypted. ZPass currently supports unencrypted exports only.",
	import_summary: "Ready to import {{n}} of {{total}} items.",
	import_summary_zero: "No items detected.",
	import_breakdown: "Breakdown",
	import_count_login: "Logins",
	import_count_card: "Cards",
	import_count_note: "Secure notes",
	import_count_identity: "Identities",
	import_count_ssh: "SSH / API keys",
	import_count_passkey: "Passkeys",
	import_count_skipped: "Skipped",
	import_warning_skipped:
		"{{n}} item(s) will be skipped (unsupported type or missing required field).",
	import_strategy_label: "Conflict",
	import_strategy_append: "Append (keep originals)",
	import_strategy_skip_dupe: "Skip duplicates by name",
	import_run: "Import",
	import_running: "Importing…",
	import_cancel: "Cancel",
	import_done: "Imported {{n}} item(s)",
	import_done_some: "Imported {{ok}}, skipped {{skip}}",
	import_partial_fail: "Imported {{ok}}, {{fail}} failed",
	import_preview: "Preview (first 5)",

	// ── Export dialog ──
	export_title: "Export vault",
	export_sub: "Save a plaintext backup of every entry on this device.",
	export_warning_title: "Sensitive data will be written in plaintext",
	export_warning_body:
		"The export file contains every account password, SSH private key, passkey private key, and TOTP secret in your vault. Store it like you would the master password — prefer an encrypted disk, password manager, or wrap it in GPG / age / 7z before sharing.",
	export_includes_label: "This export will include",
	export_includes_logins: "Logins and passwords",
	export_includes_ssh: "SSH private keys",
	export_includes_passkey: "Passkey private keys",
	export_includes_totp: "Authenticator (TOTP) secrets",
	export_includes_notes: "Secure notes, cards and identities",
	export_format_label: "Format",
	export_format_json: "ZPass JSON (plaintext)",
	export_format_json_hint:
		"schema=zpass-export-v1 · unencrypted · readable in any text editor.",
	export_confirm_password_label: "Confirm with master password",
	export_confirm_password_placeholder: "Master password",
	export_confirm_password_hint:
		"We re-verify your master password before writing the file.",
	export_cancel: "Cancel",
	export_run: "Export…",
	export_running: "Exporting…",
	export_invalid_password: "Master password is incorrect.",
	export_error_generic: "Export failed: {{message}}",
	export_done: "Exported {{n}} item(s) to {{path}}",
	export_cancelled: "Export cancelled",
	export_open_folder: "Open folder",

	// Workspace switcher —— 侧边栏顶部空间切换器
	workspace_switch: "Switch workspace",
	workspace_section_title: "Workspaces",
	workspace_new: "New workspace",
	workspace_new_label: "Name",
	workspace_new_placeholder: "e.g. Work, Family",
	workspace_create: "Create",
	workspace_cancel: "Cancel",

	// Welcome —— 首次启动欢迎页（登录 / 跳过二选一）
	welcome_brand_sub: "End-to-end encrypted · Zero knowledge",
	welcome_title: "Welcome to ZPass",
	welcome_sub:
		"Choose how you'd like to get started. You can change this later in Settings.",
	welcome_signin_title: "Sign in to your account",
	welcome_signin_desc:
		"Sync your vault across devices with end-to-end encryption.",
	welcome_signin_coming_soon: "Coming soon",
	welcome_skip_title: "Continue without account",
	welcome_skip_desc:
		"Store passwords locally on this device only. No cloud sync.",
	welcome_skip_badge: "Local",
	welcome_privacy:
		"ZPass uses zero-knowledge architecture. Your master password never leaves this device—even when you sign in.",

	// Sign in —— 云端账户登录页
	signin_back: "Back",
	signin_title: "Sign in",
	signin_sub: "Use your ZPass account email and password.",
	signin_email_placeholder: "you@example.com",
	signin_password_placeholder: "Account password",
	signin_submit: "Sign in",
	signin_loading: "Signing in…",
	signin_forgot: "Forgot password?",
	signin_create: "Create account",
	signin_err_email: "Please enter a valid email address.",
	signin_err_password: "Password cannot be empty.",
	signin_err_credentials: "Incorrect email or password.",

	// Cloud sync —— 登录/注册/设置共用 key（前缀 cloud_）
	// 登录页模式切换
	cloud_signin_tab: "Sign in instead",
	cloud_register_tab: "Create account",
	// 注册表单
	cloud_register_title: "Create your ZPass account",
	cloud_register_sub: "Your master password encrypts your vault locally — we never see it.",
	cloud_new_password_placeholder: "Master password",
	cloud_confirm_password_placeholder: "Confirm master password",
	cloud_register_submit: "Create account",
	cloud_register_loading: "Creating account…",
	// Secret Key 存档步骤
	cloud_secretkey_title: "Save your Secret Key",
	cloud_secretkey_sub: "Write it down or store it in a safe place. This is the only copy.",
	cloud_secretkey_label: "Secret Key",
	cloud_secretkey_placeholder: "Z1-...",
	cloud_secretkey_save_warning:
		"This Secret Key cannot be recovered if lost. ZPass stores it nowhere — you are the only holder. Without it, your data cannot be decrypted.",
	cloud_secretkey_saved_checkbox: "I have saved my Secret Key somewhere safe",
	cloud_continue: "Continue",
	// Server URL 配置
	cloud_server_url_label: "Server URL",
	cloud_server_url_desc: "Enter the URL of your ZPass sync server.",
	cloud_server_save: "Save",
	// 错误 key
	cloud_err_credentials: "Incorrect email, password, or Secret Key.",
	cloud_err_not_configured: "No sync server configured. Please enter a server URL above.",
	cloud_err_mfa: "Multi-factor authentication is required.",
	cloud_err_generic: "Something went wrong. Please try again.",
	cloud_err_pwd_mismatch: "Passwords do not match.",
	cloud_err_secretkey_required: "Secret Key is required to sign in.",
	cloud_err_secretkey_format:
		"That Secret Key doesn't look right — it starts with Z1- followed by your account id and the key body. Paste the exact key from when you created your account; if you don't have one yet, choose Create account.",
	// 设置区块
	cloud_settings_title: "Cloud sync",
	cloud_settings_desc: "Sync your vault securely across devices using your ZPass account.",
	cloud_not_signed_in: "Not signed in",
	cloud_signin_btn: "Sign in",
	cloud_signout: "Sign out",
	cloud_token_persisted: "token persisted",
	// 空间同步
	cloud_enable_for_space: "Enable cloud sync for this space",
	cloud_synced: "Cloud sync enabled",
	cloud_unlink: "Unlink",
	// 立即同步
	cloud_sync_now: "Sync now",
	cloud_sync_done_summary: "Pulled {{pulled}}, pushed {{pushed}}",
	// 进度阶段
	cloud_progress_pushing: "Pushing changes",
	cloud_progress_pulling: "Pulling changes",
	cloud_progress_conflict: "Awaiting conflict resolution",
	cloud_progress_done: "Sync complete",
	cloud_progress_error: "Sync error",
	// 冲突解决
	cloud_conflicts_pending: "{{count}} conflict(s) pending",
	cloud_resolve_conflicts: "Resolve conflicts",
	cloud_conflict_title: "Resolve conflicts ({{idx}} / {{total}})",
	cloud_conflict_local: "This device",
	cloud_conflict_remote: "Cloud (remote)",
	cloud_conflict_all_local: "All: keep local",
	cloud_conflict_all_remote: "All: keep remote",
	cloud_conflict_all_skip: "All: skip",
	cloud_conflict_prev: "Previous",
	cloud_conflict_next: "Next",
	cloud_conflict_duplicate: "Keep both",
	cloud_conflict_duplicate_hint: "Save both copies as separate entries",
	cloud_conflict_skip: "Skip",
	cloud_conflict_skip_hint: "Keep local, ignore remote",
	cloud_conflict_apply: "Apply all",

	// Onboarding —— 首次引导：创建第一个空间
	onboarding_back: "Back",
	onboarding_step: "Step 1 · Create your first workspace",
	onboarding_greeting: "Welcome",
	onboarding_greeting_named: "Welcome, {{name}}",
	onboarding_title: "Name your first workspace",
	onboarding_sub:
		"Workspaces are top-level containers that keep different sets of credentials fully isolated.",
	onboarding_concept:
		"A workspace is like a separate vault—use one for personal logins, another for work, another for shared family accounts. Each keeps its own items, folders and access policies.",
	onboarding_name_label: "Workspace name",
	onboarding_name_placeholder: "e.g. Personal",
	onboarding_presets_label: "Quick picks",
	onboarding_preset_personal: "Personal",
	onboarding_preset_work: "Work",
	onboarding_preset_family: "Family",
	onboarding_submit: "Create workspace",
	onboarding_creating: "Creating…",
	onboarding_foot_signed_in: "Signed in as {{email}}",
	onboarding_foot_guest: "Local mode · This device only",

	// Settings 页 —— 用户偏好集中管理（替代原设计中的 Tweaks 浮层）
	settings_title: "Settings",
	settings_subtitle: "Preferences apply instantly and are stored locally.",

	settings_section_appearance: "Appearance",
	settings_section_appearance_desc: "Customize how ZPass looks on this device.",
	settings_section_language: "Language & region",
	settings_section_language_desc: "Interface language for this device.",
	settings_section_security: "Security",
	settings_section_security_desc: "Vault protection and session policy.",
	settings_section_about: "About",
	settings_nav_group_general: "General",
	settings_nav_group_security: "Security",
	settings_nav_group_about: "About",

	settings_theme: "Theme",
	settings_theme_desc: "Choose between dark and light interface.",
	settings_theme_dark: "Dark",
	settings_theme_light: "Light",

	settings_scale: "Scale",
	settings_scale_desc: "Zoom the entire interface up or down.",
	settings_scale_80: "80%",
	settings_scale_90: "90%",
	settings_scale_100: "100% (Default)",
	settings_scale_110: "110%",
	settings_scale_125: "125%",
	settings_scale_150: "150%",

	settings_body_font: "Body font",
	settings_body_font_desc: "Use a monospaced font for the entire interface.",
	settings_body_sans: "Sans",
	settings_body_mono: "Mono",

	// Font customization
	settings_font_sans: "Sans-serif font",
	settings_font_sans_desc: "Custom font for body text and UI.",
	settings_font_mono: "Monospace font",
	settings_font_mono_desc: "Custom font for passwords, TOTP codes and code.",
	settings_font_default: "Default (Geist)",
	settings_font_default_mono: "Default (Geist Mono)",
	settings_font_loading: "Loading fonts…",
	settings_font_no_results: "No fonts found",

	settings_language: "Interface language",
	settings_language_desc: "Defaults to your system language; change anytime.",
	settings_language_system: "Follow system",
	settings_language_en: "English",
	settings_language_zh: "中文 (简体)",

	settings_lock_timeout: "Auto-lock",
	settings_lock_timeout_desc:
		"Lock the vault after this many minutes of inactivity.",

	// Settings — Spaces
	settings_section_spaces: "Spaces",
	settings_section_spaces_desc:
		"Manage your encrypted spaces. Each space has its own vault.",
	settings_space_rename: "Edit space",
	settings_space_delete: "Delete space",
	settings_space_delete_nonempty: "Empty this space before deleting it",
	settings_space_delete_title: "Delete space",
	settings_space_delete_msg:
		"This space will be removed. Only empty spaces can be deleted, so no items are affected.",
	settings_space_delete_confirm: "Delete space",
	settings_space_clear: "Clear items",
	settings_space_clear_title: "Clear items in space",
	settings_space_clear_msg:
		"All {{count}} items in {{name}} will be deleted.",
	settings_space_clear_warning:
		"This cannot be undone. These items are also removed from any synced devices.",
	settings_space_clear_confirm: "Clear items",
	settings_space_cancel: "Cancel",
	settings_space_rename_title: "Edit space",
	settings_space_rename_placeholder: "New name",
	settings_space_rename_confirm: "Save",
	settings_space_avatar_upload: "Upload avatar",
	settings_space_avatar_remove: "Remove avatar",
	settings_space_avatar_hint:
		"JPG / PNG / WebP supported. Resized to a 256×256 square automatically.",
	settings_space_avatar_error: "Failed to read image. Please try another file.",
	settings_space_items_one: "1 item",
	settings_space_items_other: "{{count}} items",
	settings_space_current: "Current",
	settings_space_create: "New space",
	settings_space_create_title: "Create new space",
	settings_space_create_name_placeholder: "Space name",
	settings_space_create_tag_placeholder: "Subtitle (optional)",
	settings_space_create_confirm: "Create",

	// Settings — Auto-lock
	settings_lock_trigger: "Also lock when",
	settings_lock_sleep: "System sleeps or screen locks",
	settings_lock_switch: "Switching to another app",
	settings_lock_close: "Closing the app window",
	settings_lock_1m: "1 minute",
	settings_lock_5m: "5 minutes",
	settings_lock_15m: "15 minutes",
	settings_lock_30m: "30 minutes",
	settings_lock_1h: "1 hour",
	settings_lock_4h: "4 hours",
	settings_lock_never: "Never",
	settings_lock_never_title: "Disable auto-lock?",
	settings_lock_never_msg:
		"Your vault will remain unlocked indefinitely. Anyone with access to this device can view your passwords.",
	settings_lock_never_confirm: "I understand, disable auto-lock",
	settings_lock_never_cancel: "Keep auto-lock enabled",

	// Settings — Close-button behaviour (Quit vs minimise to tray)
	settings_section_window: "Window",
	settings_section_window_desc:
		"Control how the app window behaves and integrates with the system tray.",
	settings_startup: "Startup",
	settings_launch_at_login: "Launch ZPass at login",
	settings_launch_at_login_desc:
		"Automatically start ZPass in the background after you log in, so your passwords are always ready.",
	settings_close_behavior: "When closing the window",
	settings_close_behavior_desc:
		"Tray mode keeps ZPass running so passwords stay one click away. The tray icon is always shown.",
	settings_close_behavior_quit: "Quit ZPass",
	settings_close_behavior_tray: "Minimise to system tray",
	settings_tray_hint:
		"Left-click the tray icon to show the window. Right-click for more options.",
	tray_menu_show: "Show ZPass",
	tray_menu_quit: "Quit ZPass",
	tray_tooltip: "ZPass",

	// Settings — Trusted device (auto-unlock on app restart)
	settings_section_trusted_device: "Trusted device",
	settings_section_trusted_device_desc:
		"Skip the master password on this device. Your encryption key is wrapped by your operating system's credential protection and bound to your current OS account.",
	settings_trusted_device_toggle: "Auto-unlock on this device",
	settings_trusted_device_toggle_desc:
		"Restart ZPass without entering your master password.",
	settings_trusted_device_unsupported:
		"Auto-unlock is not available on this device.",
	settings_trusted_device_enabled_hint:
		"Trusted on this device. Master password is not required on app restart.",
	settings_trusted_device_enable_title: "Trust this device?",
	settings_trusted_device_enable_msg:
		"Once enabled, ZPass will unlock automatically on this device after restart, without asking for your master password.",
	settings_trusted_device_enable_when_safe: "Enable only if:",
	settings_trusted_device_enable_safe_1: "This device is used only by you",
	settings_trusted_device_enable_safe_2:
		"Your OS account is protected by a strong password",
	settings_trusted_device_enable_safe_3: "The device is not shared with others",
	settings_trusted_device_enable_when_unsafe: "Do NOT enable on:",
	settings_trusted_device_enable_unsafe_1: "Shared or public computers",
	settings_trusted_device_enable_unsafe_2:
		"Devices where others have administrator access",
	settings_trusted_device_enable_password_label:
		"Confirm with your master password",
	settings_trusted_device_enable_password_placeholder: "Master password",
	settings_trusted_device_enable_confirm: "Trust this device",
	settings_trusted_device_enable_cancel: "Cancel",
	settings_trusted_device_disable_title: "Stop trusting this device?",
	settings_trusted_device_disable_msg:
		"You will need to enter your master password the next time you start ZPass on this device.",
	settings_trusted_device_disable_confirm: "Stop trusting",
	settings_trusted_device_disable_cancel: "Keep trusted",
	settings_trusted_device_err_invalid_password: "Master password is incorrect.",
	settings_trusted_device_err_unsupported:
		"Auto-unlock is not supported on this platform.",
	settings_trusted_device_err_unknown:
		"Could not enable auto-unlock. Please try again.",

	// Settings — SSH agent
	settings_section_ssh_agent: "SSH agent",
	settings_section_ssh_agent_desc:
		"Use your vault SSH keys with ssh / git directly. No private key copying required.",

	// Settings — LAN sync
	settings_section_lan_sync: "LAN sync",
	settings_section_lan_sync_desc:
		"Merge your vault with another ZPass on the same LAN; you resolve any conflicts.",
	settings_ssh_agent_loading: "Checking status…",
	settings_ssh_agent_btn_enable: "Enable",
	settings_ssh_agent_btn_disable: "Disable",
	settings_ssh_agent_status_disabled: "Service disabled",
	settings_ssh_agent_status_waiting: "Listening, agent not running",
	settings_ssh_agent_status_starting: "Starting agent…",
	settings_ssh_agent_status_connected: "Connected and ready",
	settings_ssh_agent_keys: "key(s) exposed",
	settings_ssh_agent_socket_label: "SSH_AUTH_SOCK path",
	settings_ssh_agent_copy_path: "Copy path",
	settings_ssh_agent_copy_env: "Copy shell snippet",
	settings_ssh_agent_copy_env_btn: "Copy export",
	settings_ssh_agent_env_hint:
		"Add the export line to your shell rc (~/.zshrc, ~/.bashrc, etc.) and open a new terminal.",
	settings_ssh_agent_trust_label: "Trust cache",
	settings_ssh_agent_trust_desc:
		"Apps you marked as trusted will sign without confirmation until expiry. Clear to revoke.",
	settings_ssh_agent_trust_clear: "Clear trust",
	settings_ssh_agent_audit_label: "Audit log",
	settings_ssh_agent_audit_desc:
		"Recent sign requests (memory only, cleared on app restart).",
	settings_ssh_agent_audit_show: "Show log",
	settings_ssh_agent_audit_hide: "Hide log",
	settings_ssh_agent_audit_empty: "No sign requests yet.",
	settings_ssh_agent_audit_clear: "Clear log",
	settings_ssh_agent_debug_show: "Show debug info",
	settings_ssh_agent_debug_hide: "Hide debug info",
	settings_ssh_agent_debug_control: "Control socket",
	settings_ssh_agent_debug_binary: "Agent binary",
	settings_ssh_agent_debug_no_binary: "Not located",
	settings_ssh_agent_debug_supervised: "Supervised",
	settings_ssh_agent_debug_supervised_yes: "Yes (child process)",
	settings_ssh_agent_debug_supervised_no: "No (run manually)",
	settings_ssh_agent_retry: "Retry",
	settings_ssh_agent_outcome_approved: "Approved",
	settings_ssh_agent_outcome_declined: "Declined",
	settings_ssh_agent_outcome_timeout: "Timed out",
	settings_ssh_agent_outcome_vault_locked: "Vault locked",
	settings_ssh_agent_outcome_key_not_found: "Key not found",
	settings_ssh_agent_outcome_trusted_cache: "Auto-approved",

	// SSH agent approval modal
	approval_title: "Sign request",
	approval_unknown_key: "Unknown key",
	approval_unknown_client: "Unknown process",
	approval_client_label: "From",
	approval_pid_label: "PID",
	approval_exe_hash_label: "SHA256",
	approval_trust_label: "Trust this app for",
	approval_trust_once: "This time only",
	approval_trust_1min: "1 minute",
	approval_trust_5min: "5 minutes",
	approval_trust_30min: "30 minutes",
	approval_trust_1h: "1 hour",
	approval_trust_8h: "8 hours",
	approval_approve: "Approve",
	approval_decline: "Decline",

	// SSH key generator (new SSH item dialog)
	sshkey_mode_generate: "Generate",
	sshkey_mode_import: "Import",
	sshkey_generate_hint:
		"Generate a new SSH key pair. The private key is encrypted into your vault; only the public key is shown.",
	sshkey_algo_label: "Algorithm",
	sshkey_comment_label: "Comment (recommended)",
	sshkey_comment_placeholder: "e.g. user@host",
	sshkey_generate_btn: "Generate key pair",
	sshkey_regenerate: "Regenerate",
	sshkey_generating: "Generating…",
	sshkey_public_key_label: "Public key (add to GitHub / server)",
	sshkey_fingerprint_label: "Fingerprint",
	sshkey_copy_public: "Copy",
	sshkey_copied: "Copied",
	sshkey_after_generate_hint:
		"Save the item, then paste the public key into your service (GitHub Settings → SSH keys, etc.).",

	// SSH 私钥折叠区域
	sshkey_private_key_label: "Private key",
	sshkey_show_private: "Show",
	sshkey_hide_private: "Hide",
	sshkey_copy_private: "Copy",
	sshkey_private_hidden_hint: "Private key hidden — click to reveal",
	sshkey_private_warning:
		"Treat the private key like a password. Never share it; ZPass keeps it encrypted in your vault.",

	settings_about_version: "Version",
	settings_about_build: "Build",
	settings_about_source: "Source code",

	// Tweaks / Settings
	tw_title: "Appearance",
	tw_theme: "Theme",
	tw_dark: "Dark",
	tw_light: "Light",
	tw_density: "Density",
	tw_compact: "Compact",
	tw_normal: "Normal",
	tw_comfy: "Comfy",
	tw_body: "Body font",
	tw_sans: "Sans",
	tw_mono: "Mono",
	tw_lang: "Language",
	tw_hint: "Preferences apply instantly",

	// Toast
	copied: "Copied",
	copied_label: "Copied",

	// Custom fields (Bitwarden-style)
	// Wording: replace single-word "Text/Hidden/Boolean/Linked" with
	// scenario-style labels + a one-line description, so users can tell
	// what each option does at a glance.
	custom_fields_section: "Custom fields",
	custom_fields_empty: "No custom fields yet.",
	custom_fields_add: "Add field",
	// Dropdown primary labels
	custom_fields_add_text_label: "Plain text",
	custom_fields_add_hidden_label: "Sensitive text",
	custom_fields_add_boolean_label: "Yes / No",
	custom_fields_add_linked_label: "Reference a built-in field",
	// Dropdown descriptions
	custom_fields_add_text_desc: "Visible, e.g. labels or notes",
	custom_fields_add_hidden_desc: "Masked by default, e.g. PIN or backup codes",
	custom_fields_add_boolean_desc: 'On/off flag, e.g. "2FA enabled"',
	custom_fields_add_linked_desc: "Reuse a built-in field for autofill",
	// Inline type selector keeps compact short labels
	custom_fields_type_text: "Text",
	custom_fields_type_hidden: "Hidden",
	custom_fields_type_boolean: "Yes / No",
	custom_fields_type_linked: "Linked",
	custom_fields_name_placeholder: "Field name",
	custom_fields_value_placeholder: "Value",
	custom_fields_remove: "Remove field",
	custom_fields_unnamed: "Untitled",
	custom_fields_bool_on: "Yes",
	custom_fields_bool_off: "No",
	custom_fields_link_none: "(none)",
	custom_fields_link_unavailable:
		"No built-in fields available to reference for this item type",

	// ---------------------------------------------------------------------------
	// TOTP / Authenticator
	// ---------------------------------------------------------------------------
	// 字段相关词条用于「编辑表单」与「详情面板」
	field_totp_secret: "Authenticator key",
	field_totp_secret_placeholder: "JBSW Y3DP EHPK 3PXP …",
	field_totp_code: "One-time code",
	field_totp_issuer: "Issuer",
	field_totp_issuer_placeholder: "GitHub, Google, …",
	field_totp_account: "Account",
	field_totp_account_placeholder: "user@example.com",

	// 聚合页（/totp）专用文案
	totp_title: "Authenticator",
	totp_count: "{{count}} codes",
	totp_empty: "No authenticator codes yet",
	totp_empty_hint:
		"Add a TOTP key to any login or create a dedicated authenticator entry to see live codes here.",
	totp_empty_goto_vault: "Go to vault",
	totp_select_hint: "Select an entry to view its one-time code",
	totp_edit_in_vault: "Edit in vault",
	totp_row_click_to_copy: "Click to copy code",
	totp_filter_all: "All",
	totp_filter_login: "Logins",
	totp_filter_totp: "Authenticators",
	totp_filter_empty: "No items match this filter",
	totp_meta_algorithm: "Algorithm",
	totp_meta_period: "Period",
	totp_meta_digits: "Digits",

	// TotpField 错误占位文案 —— 与 vaultErrorKind 一一对应
	totp_err_secret_missing: "No authenticator key configured",
	totp_err_secret_invalid: "Authenticator key is not valid base32",
	totp_err_locked: "Vault is locked",
	totp_err_not_found: "Entry no longer exists",
	totp_err_unknown: "Failed to generate code",
	totp_err_type_mismatch: "This entry is not an HOTP item",
	// OTP type badges — shown next to the code so the user knows which algorithm is in use
	totp_badge_totp: "TOTP · time-based",
	totp_badge_hotp: "HOTP · counter-based",
	totp_badge_steam: "Steam Guard",
	totp_label_counter: "Counter",
	totp_btn_next: "Next code",

	// ---------------------------------------------------------------------------
	// QR 扫码面板 —— ItemDialog 内嵌从二维码导入身份验证器密钥
	// ---------------------------------------------------------------------------
	qr_btn_label: "Import from QR code",
	qr_panel_title: "Import from QR code",
	qr_paste_btn: "Paste screenshot",
	qr_paste_hint: "Press ⌘V / Ctrl+V to paste a screenshot from your clipboard",
	qr_pick_file: "Choose image",
	qr_drag_hint: "… or drag an image file here",
	qr_supported_hint:
		"Supports otpauth:// QR codes from Google Authenticator, Authy (standard export), Bitwarden Authenticator, Steam, and more.",
	qr_decoding: "Decoding…",
	qr_result_ok: "QR code recognized",
	qr_meta_type: "Type",
	qr_meta_params: "Parameters",
	qr_meta_secret: "Secret",
	qr_meta_digits_short: "digits",
	qr_trust_warning:
		"Only apply if you trust the source of this QR code. ZPass won't enable the authenticator until you confirm.",
	qr_apply: "Use this key",
	qr_retry: "Try another image",
	qr_err_no_qr_title: "No QR code detected",
	qr_err_no_qr_hint:
		"Make sure the QR code is fully visible, not blurry, and that the three corner markers aren't covered.",
	qr_err_not_otpauth_title: "Not an authenticator QR code",
	qr_err_not_otpauth_hint:
		"ZPass only accepts otpauth:// QR codes. The image below contains a different kind of QR code.",
	qr_err_missing_secret_title: "QR code is missing the secret",
	qr_err_missing_secret_hint:
		"The otpauth:// URI in this image doesn't include a `secret` parameter, so no code can be generated.",
	qr_err_invalid_type_title: "Unsupported authenticator type",
	qr_err_invalid_type_hint:
		"ZPass supports TOTP / HOTP / Steam Guard. The QR code uses an unknown type segment.",
	qr_err_invalid_uri_title: "QR code is malformed",
	qr_err_invalid_uri_hint:
		"The otpauth:// URI inside the image could not be parsed.",
	qr_err_detected_content: "Detected content",
	qr_err_not_image: "Only image files are supported.",
	qr_err_too_large: "Image is too large (max 10 MB).",
	qr_err_no_image_in_clipboard: "No image found in clipboard.",
} as const;

/** 字典 key 联合类型 —— 用于 i18n t() 的类型约束 */
export type I18nKey = keyof typeof en;

/** 字典结构 —— zh.ts 通过 `Strings` 约束自身形状，确保键集合对齐 */
export type Strings = Record<I18nKey, string>;
